import type {Metadata} from "next";
import {inter} from "./ui/fonts";
import "./globals.css";
import {Navbar17} from "@/app/ui/navbar/navbar17";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="cs">
        <body
            className={`${inter.className}  antialiased w-full flex flex-col items-center justify-center px-8`}
        >
        <header className='container flex flex-col items-center justify-center'>
            <Navbar17></Navbar17>
        </header>
        <main className='container flex flex-col items-center justify-center'>
            {children}
        </main>
        <footer></footer>
        </body>
        </html>
    );
}
